#!/bin/bash
set -e
set -x

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
echo 1>&2
    echo "Could not find a MySQL database. Please add a MySQL cartridge:" 1>&2
    echo "" 1>&2
    echo "  rhc cartridge add mysql-5.1 -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "" 1>&2
    echo "and try pushing again." 1>&2
    echo 1>&2
    exit 1
fi

# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" --port "$OPENSHIFT_MYSQL_DB_PORT" -e "select * from posts;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo
    echo "Database schema not found, importing 'cake.sql' schema."
    echo
    /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" --port "$OPENSHIFT_MYSQL_DB_PORT" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/cake.sql"
    echo
    echo "done."
else
    echo "Database found, skipping import."
fi
